services:
  backend:
    build: ./backend
    image: speeddocument-backend:latest
    container_name: speeddocument_backend
    restart: always
    ports:
      - "5000:5000"
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./backend/.env

  admin:
    build: ./speeddocument-admin
    image: speeddocument-admin:latest
    container_name: speeddocument_admin
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend